apiVersion: v1
kind: Service
metadata:
  name: vl
spec:
  selector:
    app: vl
  type: NodePort
  ports:
  - nodePort: 31317
    port: 8080
    protocol: TCP
    targetPort: 8080
    targetPort: https
