apiVersion: v1
kind: Service
metadata:
  name: vl
spec:
  selector:
    app: vl
  type: NodePort
  ports:
  - nodePort: 31317
    port: 5000
    protocol: TCP
    targetPort: 5000
    targetPort: https
