# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from vl.models.base_model_ import Model
from vl import util


class ImageUpload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: str=None, image: str=None):  # noqa: E501
        """ImageUpload - a model defined in Swagger

        :param user_id: The user_id of this ImageUpload.  # noqa: E501
        :type user_id: str
        :param image: The image of this ImageUpload.  # noqa: E501
        :type image: str
        """
        self.swagger_types = {
            'user_id': str,
            'image': str
        }

        self.attribute_map = {
            'user_id': 'userId',
            'image': 'image'
        }
        self._user_id = user_id
        self._image = image

    @classmethod
    def from_dict(cls, dikt) -> 'ImageUpload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageUpload of this ImageUpload.  # noqa: E501
        :rtype: ImageUpload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this ImageUpload.


        :return: The user_id of this ImageUpload.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this ImageUpload.


        :param user_id: The user_id of this ImageUpload.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def image(self) -> str:
        """Gets the image of this ImageUpload.


        :return: The image of this ImageUpload.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this ImageUpload.


        :param image: The image of this ImageUpload.
        :type image: str
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image
