# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from vl.models.base_model_ import Model
from vl import util


class UserDataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, type: str=None, message: str=None, user_id: str=None):  # noqa: E501
        """UserDataResponse - a model defined in Swagger

        :param code: The code of this UserDataResponse.  # noqa: E501
        :type code: int
        :param type: The type of this UserDataResponse.  # noqa: E501
        :type type: str
        :param message: The message of this UserDataResponse.  # noqa: E501
        :type message: str
        :param user_id: The user_id of this UserDataResponse.  # noqa: E501
        :type user_id: str
        """
        self.swagger_types = {
            'code': int,
            'type': str,
            'message': str,
            'user_id': str
        }

        self.attribute_map = {
            'code': 'code',
            'type': 'type',
            'message': 'message',
            'user_id': 'userId'
        }
        self._code = code
        self._type = type
        self._message = message
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'UserDataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserDataResponse of this UserDataResponse.  # noqa: E501
        :rtype: UserDataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this UserDataResponse.


        :return: The code of this UserDataResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this UserDataResponse.


        :param code: The code of this UserDataResponse.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def type(self) -> str:
        """Gets the type of this UserDataResponse.


        :return: The type of this UserDataResponse.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this UserDataResponse.


        :param type: The type of this UserDataResponse.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def message(self) -> str:
        """Gets the message of this UserDataResponse.


        :return: The message of this UserDataResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this UserDataResponse.


        :param message: The message of this UserDataResponse.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserDataResponse.


        :return: The user_id of this UserDataResponse.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserDataResponse.


        :param user_id: The user_id of this UserDataResponse.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id
