# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, surname: str=None, gender: str=None, date_of_birth: str=None, place_of_birth: str=None, country: str=None):  # noqa: E501
        """User - a model defined in Swagger

        :param name: The name of this User.  # noqa: E501
        :type name: str
        :param surname: The surname of this User.  # noqa: E501
        :type surname: str
        :param gender: The gender of this User.  # noqa: E501
        :type gender: str
        :param date_of_birth: The date_of_birth of this User.  # noqa: E501
        :type date_of_birth: str
        :param place_of_birth: The place_of_birth of this User.  # noqa: E501
        :type place_of_birth: str
        :param country: The country of this User.  # noqa: E501
        :type country: str
        """
        self.swagger_types = {
            'name': str,
            'surname': str,
            'gender': str,
            'date_of_birth': str,
            'place_of_birth': str,
            'country': str
        }

        self.attribute_map = {
            'name': 'name',
            'surname': 'surname',
            'gender': 'gender',
            'date_of_birth': 'dateOfBirth',
            'place_of_birth': 'placeOfBirth',
            'country': 'country'
        }

        self._name = name
        self._surname = surname
        self._gender = gender
        self._date_of_birth = date_of_birth
        self._place_of_birth = place_of_birth
        self._country = country

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this User.


        :return: The name of this User.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this User.


        :param name: The name of this User.
        :type name: str
        """

        self._name = name

    @property
    def surname(self) -> str:
        """Gets the surname of this User.


        :return: The surname of this User.
        :rtype: str
        """
        return self._surname

    @surname.setter
    def surname(self, surname: str):
        """Sets the surname of this User.


        :param surname: The surname of this User.
        :type surname: str
        """

        self._surname = surname

    @property
    def gender(self) -> str:
        """Gets the gender of this User.


        :return: The gender of this User.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this User.


        :param gender: The gender of this User.
        :type gender: str
        """

        self._gender = gender

    @property
    def date_of_birth(self) -> str:
        """Gets the date_of_birth of this User.


        :return: The date_of_birth of this User.
        :rtype: str
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth: str):
        """Sets the date_of_birth of this User.


        :param date_of_birth: The date_of_birth of this User.
        :type date_of_birth: str
        """

        self._date_of_birth = date_of_birth

    @property
    def place_of_birth(self) -> str:
        """Gets the place_of_birth of this User.


        :return: The place_of_birth of this User.
        :rtype: str
        """
        return self._place_of_birth

    @place_of_birth.setter
    def place_of_birth(self, place_of_birth: str):
        """Sets the place_of_birth of this User.


        :param place_of_birth: The place_of_birth of this User.
        :type place_of_birth: str
        """

        self._place_of_birth = place_of_birth

    @property
    def country(self) -> str:
        """Gets the country of this User.


        :return: The country of this User.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this User.


        :param country: The country of this User.
        :type country: str
        """

        self._country = country
